### ISSUE TITLE
Wire.requestFrom() should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [Schm1tz1/arduino-ms5xxx#5] opened 2019-03-20 17:35 UTC
In the file "shab/flight_software/MS5xxx.cpp", the Wire.requestFrom() is followed by some Wire.read() and then a Wire.endTransmission(). That Wire.endTransmission() may be removed.

Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)

**Comment by Schm1tz1** [comment] 2019-03-20 19:53
Thanks for the information. I will test it before applying the changes. Feel free to do a pull request to commit your tested changes to the library ;-).

**Comment by Koepel** [comment] 2019-03-20 23:11
You are not sure that removing a bug will be better?
The link to the common mistakes is written by me, but the Arduino documentation tells the same story:

- [Wire.beginTransmission()](https://www.arduino.cc/en/Reference/WireBeginTransmission)
- [Wire.endTransmssion()](https://www.arduino.cc/en/Reference/WireEndTransmission)
- [Wire.requestFrom()](https://www.arduino.cc/en/Reference/WireRequestFrom)

**Comment by Schm1tz1** [comment] 2019-03-21 11:53
> You are not sure that removing a bug will be better?

That's not my point. It''s not about removing a bug, more testing the effect of a code change before comitting. The library is working as intended and there have been no bugs reported the last years. I'd rather call it optimization.

> The link to the common mistakes is written by me, but the Arduino documentation tells the same story:
> 
> * [Wire.beginTransmission()](https://www.arduino.cc/en/Reference/WireBeginTransmission)
> * [Wire.endTransmssion()](https://www.arduino.cc/en/Reference/WireEndTransmission)
> * [Wire.requestFrom()](https://www.arduino.cc/en/Reference/WireRequestFrom)

Fine. Links are links and code changes are code changes... Even though these changes look trivial, one needs to test the full funtionality with a mikrocontroller and sensor connected.

**Comment by Koepel** [comment] 2022-02-17 08:09
How about now ?
Do you know how to use the functions of the Wire library ?

**Comment by Schm1tz1** [comment] 2022-02-17 10:50
Yes, I do and as I told some time ago:
> Thanks for the information. I will test it before applying the changes. Feel free to do a pull request to commit your tested changes to the library ;-).

You probably have a running setup in place, I don't even have a sensor of that type anymore. So please - change, test, verify, do a pull request an I will have a look. I know it's a one-liner, but I will not push untested changes into a community project - this is not how software development and testing work.
Do you know how to contribute to a github project? You know forks, branches, pull requests?

**Comment by Koepel** [comment] 2022-02-17 13:26
Sorry, but I don't have the sensor.
I started making issues because many did it wrong and I had to explain it many times in the arduino forum how to use the Wire functions. The extra Wire.endTransmission() might create a unwanted I2C bus activity. I understand your point, but I see not problem in fixing the bug.
Could you meet me in the middle and keep this issue open ?

**Comment by Schm1tz1** [comment] 2022-02-17 15:08
Sure. It is already in testing branch but not yet tested ;-).
https://github.com/Schm1tz1/arduino-ms5xxx/compare/testing

**Comment by Schm1tz1** [comment] 2022-02-17 15:12
Cannot find the original MS5607 but at least 5611 you can get on ebay from China. Either someone from the community runs at least some test overnight or I will have to buy one and wait a few weeks for them to arrive.

**Comment by Schm1tz1** [comment] 2023-07-31 19:28
Merged.

**Closed as completed by Schm1tz1** 2023-07-31 19:28 UTC
Labels: bug
