### ISSUE TITLE
MS5xxx example does not work on nRF52832

### ISSUE THREAD

**Issue by mcm001** [Schm1tz1/arduino-ms5xxx#7] opened 2021-02-24 13:50 UTC
I used a program based off the example sketch to print the calibration data and current temperature from my MS5607 barometer. On the nRF52832 Feather from Adafruit, it produces the following:

```
Starting on MS5xxx
C0: 20
C1: 4294967039
C2: 4294967039
C3: 4294967039
C4: 4294967039
C5: 4294967039
C6: 4294967039
C7: 4294967039
-11258997720986.12 deg c
-11258997720986.12 deg c
-11258997720986.12 deg c
```
However, if we upload it to an ESP32 Feather on the same board with the same hardware, we get the following:

```
Starting on MS5xxx
C0: 20
C1: 37555
C2: 34296
C3: 24510
C4: 23248
C5: 34466
C6: 28969
C7: 53513
11.23 deg c
11.25 deg c
11.25 deg c
```

I further verified that my sensor was working correctly by writing my own code to print out PROM values:

```cpp
  Wire.beginTransmission(ADDRESS);
  Wire.write(0xA2);
  Wire.endTransmission();
  Wire.requestFrom(ADDRESS, 2);
  uint8_t higher_8 = Wire.read();
  uint8_t lower_8 = Wire.read();
  uint16_t value = (higher_8 << 8) | lower_8; // Read the first 8 bits; shift them left 8; OR with the next 8 bits
  Serial.print("Higher 8: "); Serial.print(higher_8, BIN); Serial.print("Lower 8: "); Serial.print(lower_8, BIN); Serial.print("Full: "); Serial.println(value, DEC); 
```

Which printed the correct value for A2

After digging into the library, I noticed calls to ` _Wire->endTransmission(true);` after reading bytes from serial; removing these calls caused the calibration readings and read temperature to be equivalent to with the ESP32. Why is this function call present after reading bytes from i2c?

**Comment by mcm001** [comment] 2021-02-24 13:54
When first debugging I thought the use of `unsigned int`s instead of `uint(8/16)_t` might be problematic, but it didn't cause any issues

**Comment by Schm1tz1** [comment] 2023-07-31 19:18
Sorry, somehow missed the notification on this issue - seems to be the same issue as https://github.com/Schm1tz1/arduino-ms5xxx/issues/5

**Comment by Schm1tz1** [comment] 2023-07-31 19:22
As it seems, the EndTransmission only causes issues on _some_ microcontrollers. Will add a fix to this library.

**Comment by Schm1tz1** [comment] 2023-07-31 19:27
Duplicate of #5

**Closed as completed by Schm1tz1** 2023-07-31 19:27 UTC
Labels: duplicate

**Comment by mcm001** [comment] 2023-08-10 05:54
Thanks for root causing this! Totally forgot I'd made this issue. Gotta say this (and another fun platform specific arithmetic bug) drove me mad a couple years ago.
