### ISSUE TITLE
problem with Arduino 101

### ISSUE THREAD

**Issue by hb9fbk** [Schm1tz1/arduino-ms5xxx#2] opened 2017-03-02 11:25 UTC
Hello Roman,
I have a problem with Arduino-MS5xxx library (Using MS5607 Parallax) with Arduino 101, Arduino IDE 1.6.13 and 1.8.1.
I tested with Arduino 2009, Mega and Mega R3 and everything works very well.
I am a beginner and I can not find a solution.

I tried the example "29124-Altimeter-Module-KickStart" on https://www.parallax.com/product/29124 and it works but I need the very low pressure and temperature for a weather balloon.

I apologize for my English, and for how to report a problem that maybe is not the correct way.

Best regards

Flavio

**Comment by Schm1tz1** [comment] 2017-03-02 14:44
Hi Flavio,

could you please tell me what the problem is ? What are you doing, how is the setup, what is the output. Without any details I can't even guess what's happening ;-).
I don't have an Arduino 101, but the code was tested with old Arduino 0.9, 1.0 and also the newest IDE. It works with many Arduino-boards, even Arduino ATTINY-USB and ESP8266. The code should be ok.
Maybe you have to check which pins are used for communication and change them in the code.
Please post a simple example and the error message if there is one.

Cheers
Roman

**Comment by hb9fbk** [comment] 2017-03-02 17:05
Hello Roman,
Initial situation: Library MS5xxx 1.0.2 -> as "Test" (the original released in your library) -> response "Error connecting ...". no other connection.
The pins (A4) and SDA (A5) SCL are connected properly. The pins are not failures as I tried high I2C sensors and example of "Parallax" I reported first message on MS5607 (addr 0x76). When I compile the sketch without errors.
If you run the same example above of Arduino Mega 2009 and presents no problems (I just repeated the tests.
I can tell you that I also tested the following sensors: TLS2561, si1145, BME280 and work. I also read that there may be problems with the libreriy that do not go on Arduino 101 perhaps to problems with INTEL CURIE.
I'm sorry but I do not have sufficient knowledge to give other explanations.

regards
Flavio

**Comment by Schm1tz1** [comment] 2017-03-02 18:44
Ok, that at least give a hint. I don't have a 101 otherwise I could test easily. The code is pretty simple and using the Wire-Library. So if you used the Wire-Library before with 101, it should work. The I2C-communication seems to fail in the very beginning.

I have some ideas:

1. Maybe the pin configuration/mapping is not ok. Maybe check if the pins for SDA and SCL are mapped correctly and not exchanged. Maybe with 101 something is different...

2. Is the protocol selected correctly ? You really need to pull the PS high (to VCC) to have I2C activated. Keeping the pin floating won't work.

3. Check the I2C-Address twice. There is some I2C-Scanner on the web or even as an example. If you already worked with it at 0x76 it should be fine. For MS5xxx the standard value 0x76 is used.

4. Did you try the Parallax-Example on Arduino 101 ? I am not sure whether internal pull-up-resistors are implemented in the Inter Curie, so that might be an issue. It is just a speculation. In principle one has to take a loot at the communication with an oscilloscope or logic analyzer or something.

**Comment by Schm1tz1** [comment] 2017-03-02 18:44
Where did you read that there are problems with Arduino 101 ? Maybe from that one can find out what is going on.

**Comment by hb9fbk** [comment] 2017-03-05 13:56
hello Roman,
to answer:
1- SDA and SCL are mapped correctly.
2- The protocol is selected properly, PS (Vcc)
3- I2C address is 0x76.
4- Regarding the example of parallax does not work now. I thought it worked only because it indicated the same height is that of my home (randomness).

These days I have tried to understand the I2C protocol and I tried to make it in writing one program that currently runs on Arduino 2009 and 101.
Unfortunately the beginner and I can not understand in detail the difference between your library and what I wrote. I can send it (I can copy it here?).

Problems with the declaration of variables?
Wire.endTransmission () after Wire.available ()? I would not write wrong things.

regards
Flavio

**Comment by Schm1tz1** [comment] 2017-03-10 14:04
Hi Flavio,

do you still have problems with the Code ? You don't need to understand I2C completely. One important this is that there are Start and Stop commands being sent. The "endTransmission" ends the current command and sends it to the I2C-bus. Try some simple Wire-Library-Example. There is a I2C-Scanner somewhere on arduino.cc or even in the examples. It should see the sensor if connected correctly. 

Does it have a LED for power/communication ? Mine is integrated in a air-tight detector so I cannot see it. From what I remember there is a green power led and a red one for communication.

What do the levels of 101 look like ? 5V or 3V ? Maybe there is a problem with low voltages an maybe a voltage drop due to cables/connections...

I don't understand "Wire.endTransmission () after Wire.available ()? I would not write wrong things." - this is the way how you send commands over I2C using the Wire library.

Is the usage or Wire with 101 the same as for the others or do you need a different configuration or instance of the Wire-class ?

If this is not a general issue with the library I will close this thread as this is confusing. I think there is a problem with your setup to be honest.

Cheers,
Roman

**Comment by Schm1tz1** [comment] 2017-03-17 18:07
Any news here ? Would be nice to learn what is going wrong with 101. Anyway - as it does not look like a problem in this code as it is using (more or less) standard communication libraries I am closing this issue.

**Closed as completed by Schm1tz1** 2017-03-17 18:07 UTC
Labels: question
